version: "3.8"

services:
  db:
    image: postgres:14
    container_name: alexnum_postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    env_file:
      - ./.env
    ports:
      - "5433:5432"
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: alexnum_bot
    restart: always
    command: python main.py
    volumes:
      - .:/code
    env_file:
      - ./.env  

volumes:
  postgres_data: